[workspace]
authors = ["Doug Latornell <dlatornell@eoas.ubc.ca>"]
channels = ["conda-forge"]
name = "moad-docs"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
repository = "https://github.com/UBC-MOAD/docs"
documentation = "https://ubc-moad-docs.readthedocs.io/en/latest/"

[tasks]
docs = "make clean html"
linkcheck = "make clean linkcheck"
update-reqs = "python -m pip list --format=freeze >> requirements.txt"

[dependencies]
python = "3.14.*"
# For repo QA
pip = "*"
pre-commit = "*"
# For building the docs
docutils = "==0.22.4"
nbsphinx = "==0.9.8"
sphinx = "==9.1.0"
sphinx-notfound-page = "==1.1.0"
sphinx-copybutton = "==0.5.2"
commonmark = "==0.9.1"
recommonmark = "==0.7.1"
mock = "==5.2.0"
pillow = "==12.2.0"

[pypi-dependencies]
# Have to use PyPI because of a bug re: Sphinx<9 in the conda-forge recipe
sphinx-rtd-theme = "==3.1.0"
