# Automatically assign new or reopened issues and pull requests in this
# repo to Doug

name: Assign Issue/PR

permissions: {}

on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
    types:
      - reopened
      - opened

jobs:
  auto_assign:
    name: Automatically assign new or reopened issues and pull requests to Doug
    permissions:
      issues: write  # Required to add assignee to issue
      pull-requests: write  # Required to add assignee to PR
    uses: UBC-MOAD/gha-workflows/.github/workflows/auto-assign.yaml@main  # zizmor: ignore[unpinned-uses]
