name: sphinx-linkcheck

permissions: {}

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: 43 4 5 * *  # 04:43 UTC on the 5th day of each month

jobs:
  sphinx-linkcheck:
    name: Sphinx linkcheck
    permissions:
      contents: read  # Required to read the repo contents

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-sphinx-linkcheck.yaml@main  # zizmor: ignore[unpinned-uses]
