# Updates the pixi lockfile and create a pull request containing the changes.

name: update-pixi-lockfile

permissions: {}

on:
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  workflow_dispatch:

  schedule:
    - cron: 43 5 5 * *  # 05:43 UTC on the 5th day of each month

jobs:
  update-pixi-lockfile:
    name: Update pixi lockfile
    permissions:
      contents: write  # Required to update the pixi lockfile
      pull-requests: write  # Required to create a pull request containing the changes

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-lockfile-updater.yaml@main  # zizmor: ignore[unpinned-uses]
